- op: add
  path: /spec/kubeadmConfigSpec/postKubeadmCommands/-
  value: "/tmp/updateKubeapi.sh"
    

- op: add
  path: /spec/kubeadmConfigSpec/files/- 
  value:
    path: /tmp/updateKubeapi.sh
    permissions: "0755"
    content: |
        #!/bin/bash
        export VERSION=v4.44.2
        export BINARY=yq_linux_amd64
        wget https://github.com/mikefarah/yq/releases/download/$VERSION/$BINARY.tar.gz -O /tmp/yq.tar.gz
        tar xvf /tmp/yq.tar.gz -C /tmp
        mv $BINARY /tmp/yq
        /tmp/yq -i '.spec.containers[0].command += "--oidc-client-id=kubelogin"' /etc/kubernetes/manifests/kube-apiserver.yaml
        /tmp/yq -i '.spec.containers[0].command += "--oidc-groups-claim=groups"' /etc/kubernetes/manifests/kube-apiserver.yaml
        /tmp/yq -i '.spec.containers[0].command += "--oidc-issuer-url=https://dex.k8s.edge.ashman.world"' /etc/kubernetes/manifests/kube-apiserver.yaml
        /tmp/yq -i '.spec.containers[0].command += "--oidc-username-claim=email"' /etc/kubernetes/manifests/kube-apiserver.yaml


#- op: add
#  path: /spec/kubeadmConfigSpec/files/- 
#  value:
#    path: /tmp/installCilium.sh
#    permissions: "0755"
#    content: |
#        #!/bin/bash
#        export KUBECONFIG=/etc/kubernetes/admin.conf
#        export HELM_CONFIG_HOME=/tmp
#        export HELM_DATA_HOME=/tmp
#        export HELM_CACHE_HOME=/tmp
#        kubectl -n kube-system delete ds kube-proxy
#        kubectl -n kube-system delete cm kube-proxy
#        iptables-save | grep -v KUBE | iptables-restore
#    
#        curl -o /tmp/helm.tar.gz "https://get.helm.sh/helm-v3.15.2-linux-amd64.tar.gz"
#        tar xvf /tmp/helm.tar.gz -C /tmp
#        chmod a+x /tmp/linux-amd64/helm
#    
#        /tmp/linux-amd64/helm repo add cilium https://helm.cilium.io/
#        /tmp/linux-amd64/helm install cilium cilium/cilium --version 1.15.6 --set kubeProxyReplacement=true --set k8sServiceHost=10.40.2.200 --set k8sServicePort=6443 --namespace kube-system
#        rm -rf /tmp/linux-amd64 && rm /tmp/helm.tar.gz
#
