apiVersion: v1
data:
  format: Y2xvdWQtY29uZmln
  userData: I2Nsb3VkLWNvbmZpZwp1c2VyczogCi0gbmFtZTogdXNlcgogIHN1ZG86IEFMTD0oQUxMKSBOT1BBU1NXRDpBTEwKICBncm91cHM6IFt3aGVlbF0KICBzc2hfYXV0aG9yaXplZF9rZXlzOgogIC0gc3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUdiemNiMjNMNXdHK0lVdHNyOWljMU1NWlBtK2JNaGxWWDZTQjJPdWFlUzkgYXNoZXJAaW5mcmEta3ViZS0xCg==
kind: Secret
metadata:
  creationTimestamp: "2024-06-12T14:24:27Z"
  labels:
    environment.metal3.io: baremetal
  name: cloud-init-updates
  namespace: baremetal-operator-system
  resourceVersion: "3253"
  uid: 3e270782-1fe1-406f-935e-ccc797fa3265
type: Opaque
