packer {
  required_plugins {
    proxmox = {
      version = "~> 1"
      source  = "github.com/hashicorp/proxmox"
    }
    ansible = {
      version = "~> 1"
      source = "github.com/hashicorp/ansible"
    }
  }
}

variable "proxmox_api_url" {
    type = string
}

variable "proxmox_api_token_id" {
    type = string
}

variable "proxmox_api_token_secret" {
    type = string
    sensitive = true
}
variable "vm_id" {
    type = string
}
variable "node" {
    type = string
}

source "proxmox-iso" "autogenerated_1" {
    proxmox_url = "${ var.proxmox_api_url }"
    username = "${ var.proxmox_api_token_id }"
    token = "${ var.proxmox_api_token_secret }"
    insecure_skip_tls_verify = true

    boot_iso {
        type = "scsi"
        iso_file = "ISO:iso/debian-12.9.0-amd64-netinst.iso"
        unmount = true
        iso_storage_pool = "local"
    }

    node = "${ var.node }"
    vm_id = "${ var.vm_id }"
    vm_name = "debian12"
    template_description = "Debian 12 Template"

    cpu_type = "host"

    qemu_agent = true

    scsi_controller = "virtio-scsi-pci"

    disks {
        disk_size = "30G"
        format = "raw"
        storage_pool = "local-lvm"
        # storage_pool_type = "zfs"
        type = "virtio"
    }

    # VM CPU Settings
    cores = "2"
    
    # VM Memory Settings
    memory = "4096" 

    # VM Network Settings
    network_adapters {
        model = "virtio"
        bridge = "svcnet"
        firewall = "false"
    } 
    
    boot_command = ["<esc><wait>auto url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg<enter>"]
    boot_wait    = "10s"
    communicator            = "ssh"

    http_directory          = "http" 

    ssh_username            = "root"
    #ssh_password = "packer"
    ssh_private_key_file    = "~/.ssh/id_ed25519"

    ssh_timeout             = "30m"
    ssh_pty                 = true

    # VM Cloud-Init Settings
    cloud_init = true
    cloud_init_storage_pool = "local-lvm"
}

build {
    sources = ["source.proxmox-iso.autogenerated_1"]

    provisioner "file" {
        destination = "/etc/cloud/cloud.cfg"
        source      = "http/cloud.cfg"
    } 

    provisioner "ansible" {
      playbook_file = "../../ansible/ipajoin.yaml"
      use_proxy = false
    }

}

