- name: Configure IPA DNS
  hosts: ipa01
  gather_facts: yes
  become: true
  module_defaults:
    freeipa.ansible_freeipa.ipadnsrecord:
      ipaadmin_password: "{{ ipaadmin_password }}"
    freeipa.ansible_freeipa.ipadnsconfig:
      ipaadmin_password: "{{ ipaadmin_password }}"
    freeipa.ansible_freeipa.ipadnszone:
      ipaadmin_password: "{{ ipaadmin_password }}"
  tasks:
    - name: Configure Global DNS
      freeipa.ansible_freeipa.ipadnsconfig:
        forwarders: "{{ ipa_dns.config.forwarders }}"
        forward_policy: first

    - name: Create Reverse DNS Zones
      freeipa.ansible_freeipa.ipadnszone:
        name_from_ip: "{{ item.ip }}"
        dynamic_update: "{{ item.dynamic_update }}"
        allow_sync_ptr: "{{ item.allow_sync_ptr }}"
        state: present
      loop: "{{ ipa_dns.reverse_zones }}"

    - name: Create DNS Zones
      freeipa.ansible_freeipa.ipadnszone:
        name: "{{ item.name }}"
        dynamic_update: "{{ item.dynamic_update }}"
        skip_overlap_check: "{{ item.skip_overlap_check }}"
        allow_sync_ptr: "{{ item.allow_sync_ptr }}"
        state: present
      loop: "{{ ipa_dns.zones }}"


