- name: Deploy infrastructure
  hosts: localhost
  connection: local
  
  tasks:
    
  - name: Destroy freeipa nodes on proxmox
    community.general.terraform: 
      project_path: ../../terraform
      state: absent
      complex_vars: true
      variables:
        dns_server: "{{ dns_server }}"
        proxmox_host: "{{ proxmox_host }}"
        proxmox_user: "{{ proxmox_user }}"
        proxmox_password: "{{ proxmox_password }}"
        proxmox_datastore_id: "{{ proxmox_datastore_id }}"
        vm_user: "{{ ansible_user }}"
        vm_user_ssh_key: "{{ ssh_pub_key }}"
        vm_template_id: "{{ vm_template_id }}"
        master_nodes: "{{ master_nodes }}"
        master_count: "{{ master_count }}"
        master_cpu: "{{ master_cpu }}"
        master_memory: "{{ master_memory }}"
        disk_size: "{{ disk_size }}"
        storage_pool: "{{ storage_pool }}"
        bridge: "{{ bridge }}"
        tag: "{{ tag }}"
        #     cloud_image: "{{ cloud_image_url }}"
        #        vm_id: "{{ vm_id }}"
        service_name: "{{ service_name }}"
