
- name: Configure IPA DNS recursive
  hosts: ipaserver
  gather_facts: yes
  become: true
  module_defaults:
    freeipa.ansible_freeipa.ipadnsrecord:
      ipaadmin_password: "{{ ipaadmin_password }}"
    freeipa.ansible_freeipa.ipadnsconfig:
      ipaadmin_password: "{{ ipaadmin_password }}"
  tasks:
    - name: Add recursive allow to config
      ansible.builtin.lineinfile:
        dest: /etc/named/ipa-options-ext.conf
        line: 'allow-recursion { any; };'
    - name: Restart
      ansible.builtin.reboot:
        reboot_timeout: 3600

