- name: Deploy infrastructure
  hosts: localhost
  tasks:
  - meta: refresh_inventory
  - ansible.builtin.add_host: 
      name: "{{ item }}.{{ dns_zone }}"
      group: ipaserver
    loop: "{{ groups['freeipaservers'] | list  }}"
