---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: addons
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./kubernetes/clusters/overlays/addons
  prune: true
  sourceRef:
    kind: "GitRepository"
    name: "flux-system"
