apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: kube-cluster
  namespace: baremetal-operator-system
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/18
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: TalosControlPlane
    name: kube-cluster-controlplane
    namespace: baremetal-operator-system
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: Metal3Cluster
    name: kube-cluster
    namespace: baremetal-operator-system
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3Cluster
metadata:
  name: kube-cluster
  namespace: baremetal-operator-system
spec:
  controlPlaneEndpoint:
    host: 10.40.2.100
    port: 6443
  noCloudProvider: true
---
## Control plane configs

apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: kube-cluster-controlplane
spec:
  version: v1.30.1
  replicas: 1
  infrastructureTemplate:
    kind: Metal3MachineTemplate
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    name: kube-cluster-controlplane
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      talosVersion: v1.7.4
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: kube-cluster-controlplane
  namespace: baremetal-operator-system
spec:
  nodeReuse: false
  template:
    spec:
      automatedCleaningMode: metadata
      hostSelector: 
        matchLabels: 
          role: master
      dataTemplate:
        name: kube-cluster-controlplane-template
      image:
        checksum: 55e20d2d944a468182f13138e65fc61d6772b516ceaced797d9096f616c1b111
        checksumType: sha256
        format: qcow2
        url: http://10.40.0.4/metal-amd64.qcow2
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: kube-cluster
    nodepool: nodepool-0
  name: kube-cluster
  namespace: baremetal-operator-system
spec:
  clusterName: kube-cluster
  replicas: 0
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: kube-cluster
      nodepool: nodepool-0
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: kube-cluster
        nodepool: nodepool-0
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: TalosConfigTemplate
          name: kube-cluster-workers
      clusterName: kube-cluster
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: Metal3MachineTemplate
        name: kube-cluster-workers
      nodeDrainTimeout: 0s
      version: v1.29.0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: kube-cluster-workers
  namespace: baremetal-operator-system
spec:
  nodeReuse: false
  template:
    spec:
      automatedCleaningMode: metadata
      hostSelector: 
        matchLabels: 
          role: worker
      dataTemplate:
        name: kube-cluster-workers-template
      image:
        checksum: 55e20d2d944a468182f13138e65fc61d6772b516ceaced797d9096f616c1b111
        checksumType: sha256
        format: qcow2
        url: http://10.40.0.4/metal-amd64.qcow2
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: kube-cluster-workers
spec:
  template:
    spec:
      generateType: join
      talosVersion: v1.7.4
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3DataTemplate
metadata:
  name: kube-cluster-controlplane-template
  namespace: baremetal-operator-system
spec:
  clusterName: kube-cluster
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3DataTemplate
metadata:
  name: kube-cluster-workers-template
  namespace: baremetal-operator-system
spec:
  clusterName: kube-cluster
