apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio
resources:
- namespace.yaml
- ../../../bases/minio
patches: 
- target: 
    kind: HelmRelease
  path: minio-patch.yaml
