apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster.yaml
- kubeadmconfigtemplate.yaml
- kubeadmcontrolplane.yaml
- machinedeployment.yaml
- machinetemplates.yaml
- metal3cluster.yaml
- metal3datatemplate.yaml
