apiVersion: v1
stringData:
  redfish.conf: |
        SUSHY_EMULATOR_TAPO_DRIVER = True
        SUSHY_EMULATOR_TAPO_SYSTEMS = [
                    {
                        u'uuid': u'<name of node>',
                        u'name': u'<not used but must be set to something>',
                        u'address': u'<Tapo P100 IP',
                        u'power_state': u'Off',
                        u'amt': False,
                        u'last_updated': '',
                        u'tapo_username': u'<TP link Username>',
                        u'tapo_password': u'<TP Link Password',
                        u'nics': [
                            {u'address': u'00:5c:52:31:3a:9c'}
                        ]
                    },
                    {
                        u'uuid': u'<name of node>',
                        u'name': u'<not used but must be set to something>',
                        u'power_state': u'Off',
                        u'amt': True,
                        u'amt_address': u'<AMT static IP address>',
                        u'amt_password': u'<AMT Password>',
                        u'last_updated': '',
                        u'nics': [
                            {u'address': u'00:5c:52:31:3a:9c'}
                        ]
                    },
        ]

kind: Secret
metadata:
  name: redfish-config
  namespace: baremetal-operator-system
type: Opaque
