apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redfish-emulator
  name: redfish-emulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redfish-emulator
  template:
    metadata:
      labels:
        app: redfish-emulator
    spec:
      containers:
      - name: emulator
        image: ghcr.io/ashmantis1/sushy-tools-baremetal/emulator
        imagePullPolicy: Always
        env: 
          - name: SUSHY_EMULATOR_CONFIG
            value: /config/redfish.conf
        securityContext: 
          capabilities: 
            add: ["NET_RAW"]
        volumeMounts: 
          - mountPath: "/config"
            name: config
            readOnly: true
      volumes: 
        - name: config
          secret:
            secretName: redfish-config
            items: 
              - key: redfish.conf
                path: redfish.conf
