apiVersion: v1
kind: Service
metadata:
  labels:
    app: redfish-emulator
  name: redfish-emulator
spec:
  clusterIP: 10.43.51.158
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: redfish-emulator
    #   type: LoadBalancer
