apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: projectsveltos
resources:
  - ../../../bases/projectsveltos
  #  - cluster-issuer.yaml
patches:
  - target: 
      kind: HelmRelease
    path: projectsveltos-patch.yaml
