- name: Create certs directory
  ansible.builtin.file:
    path: "{{ certificate_dir }}"
    state: directory

- name: Request IPA certificate for host
  ansible.builtin.shell: "ipa-getcert request -K HTTP/$(hostname) -k {{ certificate_dir }}/tls.key -f {{ certificate_dir }}/tls.crt -g 2048 -D $(hostname)"
  become: true
  register: out
  changed_when: out.rc == 0
  failed_when: out.rc != 0 and out.rc != 2

- name: Pause for certificate
  ansible.builtin.pause:
    seconds: 5

- name: Set ceritifcate file permissions
  ansible.builtin.file:
    path: "{{ certificate_dir }}"
    state: directory
    recurse: true
    mode: '0755'
    owner: "{{ cert_owner }}"
    group: "{{ cert_owner }}"
