---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certman-leases-role
  labels:
    app.kubernetes.io/instance: cert-manager
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
--- 
# Role binding for cert-manager-ca-injector to access leases
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: certman-cainjector-leases-permissions
  labels:
    app.kubernetes.io/instance: cert-manager
subjects:
- kind: ServiceAccount
  name: cert-manager-cainjector
  namespace: cert-manager
roleRef:
  kind: ClusterRole
  name: certman-leases-role  
  apiGroup: rbac.authorization.k8s.io
--- 
# Role binding for cert-manager to access leases
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: certman-user-leases-permissions
  labels:
    app.kubernetes.io/instance: cert-manager
subjects:
- kind: ServiceAccount
  name: cert-manager
  namespace: cert-manager
roleRef:
  kind: ClusterRole
  name: certman-leases-role  
  apiGroup: rbac.authorization.k8s.io