apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openbao
resources:
  - ../../../bases/openbao
  - namespace.yaml

patches:
  - target:
      kind: HelmRelease
    path: ./openbao-patch.yaml
