# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openbao
  namespace: openbao
spec:
  values: 
    ui:
      enabled: true
    server:
      ingress:
        enabled: true
        hosts:
          - host: vault.infra.edge.ashman.world

