---
# tasks file for proxmox_nodes

- name: Initialise templates variable
  ansible.builtin.set_fact:
    proxmox_nodes_templates: "{{ (proxmox_nodes_templates | default([])) + [node_templates[item][vm.template]] }}"
  loop: "{{ vm.target_nodes }}"

- name: Initialise working directory
  ansible.builtin.include_tasks: init_workdir.yaml

- name: Template files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ workdir }}/terraform/{{ item | basename }}"
  with_fileglob:
    - ../templates/*.tf

- name: Create Infrastructure
  ansible.builtin.include_tasks: run_terraform.yaml

