- name: Deploy nodes on proxmox
  community.general.terraform: 
    project_path: "{{ role_path }}/files/terraform"
    state: "{{ state }}"
    force_init: true
    complex_vars: true
    backend_config:
      bucket: "{{ s3.bucket }}"
      key: "{{ service_name }}"
      access_key: "{{ s3.access_key }}"
      secret_key: "{{ s3.secret_key }}"
      region: 'auto'
      skip_credentials_validation: 'true'
      skip_region_validation: 'true'
      skip_requesting_account_id: 'true'
      skip_metadata_api_check: 'true'
      skip_s3_checksum: 'true'
    workspace: "tfstate"
    variables:
      proxmox_host: "{{ proxmox_host }}"
      proxmox_user: "{{ proxmox_user }}"
      proxmox_password: "{{ proxmox_password }}"
      proxmox_tls_insecure: "{{ proxmox_tls_insecure }}"
      proxmox_datastore_id: "{{ proxmox_datastore_id }}"
      vm_user: "{{ ansible_user }}"
      vm_templates: "{{ proxmox_nodes_templates }}"
      nodes: "{{ vm.target_nodes }}"
      node_count: "{{ vm.count }}"
      primary_count: "{{ vm.primary_count }}"
      cpu: "{{ vm.cpu }}"
      memory: "{{ vm.memory }}"
      disk_size: "{{ vm.disk_size }}"
      storage_pool: "{{ vm.storage_pool }}"
      network_subnet: "{{ vm.network_subnet }}"
      network_mask: "{{ vm.network_mask }}"
      network_gateway: "{{ vm.network_gateway }}"
      network_start_ip: "{{ vm.network_start_ip }}"
      description: "{{ vm.description }}"
      bridge: "{{ vm.bridge }}"
      tag: "{{ vm.tag }}"
      tags: "{{ vm.tags }}"
      search_domain: "{{ vm.search_domain }}"
      dns_server: "{{ vm.dns_server }}"
      vm_user_ssh_key: "{{ vm.ssh_pub_key }}"
      service_name: "{{ service_name }}"
  register: tf_out_out
  environment:
    TF_DATA_DIR: "{{ workdir }}/tf/data/"
    AWS_ENDPOINT_URL_S3:  "{{ s3.endpoint_url }}"

- meta: refresh_inventory
