
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: kube-cluster
  namespace: baremetal-operator-system
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/18
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: kube-cluster
    namespace: baremetal-operator-system
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: Metal3Cluster
    name: kube-cluster
    namespace: baremetal-operator-system
