- name: Ensure core services are started
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
  register: result
  with_items:
    - keepalived
    - pihole-FTL
  failed_when:
    - result.failed == true
    - '"Could not find service" not in result.msg'

- name: Ensure unbound service is started
  ansible.builtin.service:
    name: unbound
    state: started
  when: enable_unbound
  register: result
  failed_when:
    - result.failed == true
    - '"Could not find unbound service" not in result.msg'

- name: "Determine Pi-hole host IPs"
  ansible.builtin.set_fact:
    pihole_local_ipv4: "{{ pihole_vip_ipv4.split('/')[0] }}"
    pihole_local_ipv6: "{% if enable_ipv6_support == true %} '{{ pihole_vip_ipv6.split('/')[0] }}' {% else %} IPv6 Support Disabled. {% endif %}"

- name: "INFORMATION"
  ansible.builtin.debug:
    msg:
      - "Make sure to point your DNS server settings here:"
      - "DNSv4: {{ pihole_local_ipv4 }}"
      - "DNSv6: {{ pihole_local_ipv6 }}"
  when: inventory_hostname in groups['master']
