- name: Create IPA Hostgroups
  freeipa.ansible_freeipa.ipahostgroup:
    name: "{{ item.name }}"
    state: present
    ipaadmin_password: "{{ ipaadmin_password }}"
  loop: "{{ ipa_hostgroups }}"

- name: Create IPA User Groups
  freeipa.ansible_freeipa.ipagroup:
    groups: "{{ ipa_usergroups }}"
    ipaadmin_password: "{{ ipaadmin_password }}"

- name: Create automember rules
  freeipa.ansible_freeipa.ipaautomember:
    name: "{{ item.name }}"
    description: "{{ item.description | default ('created by ansible') }}"
    automember_type: "{{ item.automember_type }}"
    inclusive: "{{ item.inclusive | default([]) }}"
    exclusive: "{{ item.exclusive | default([]) }}"
    state: present
    ipaadmin_password: "{{ ipaadmin_password }}"
  loop: "{{ ipa_automember_rules }}"

- name: Create Service Accounts
  freeipa.ansible_freeipa.ipauser:
    update_password: on_create
    users: "{{ ipa_service_accounts }}"
    ipaadmin_password: "{{ ipaadmin_password }}"

- name: Create IPA privileges
  freeipa.ansible_freeipa.ipaprivilege:
    name: "{{ item.name }}"
    permission: "{{ item.permission }}"
    ipaadmin_password: "{{ ipaadmin_password }}"
  loop: "{{ ipa_privileges }}"

- name: Create IPA roles
  freeipa.ansible_freeipa.iparole:
    name: "{{ item.name }}"
    user: "{{ item.user }}"
    privilege: "{{ item.privilege }}"
    ipaadmin_password: "{{ ipaadmin_password }}"
  loop: "{{ ipa_roles }}"

- name: Create HBAC Rules
  freeipa.ansible_freeipa.ipahbacrule:
    name: "{{ item.name }}"
    description: "{{ item.description | default ('created by ansible') }}"
    hostgroup: "{{ item.hostgroup }}"
    group: "{{ item.group }}"
    servicecategory: "{{ item.servicecategory | default('') }}"
    ipaadmin_password: "{{ ipaadmin_password }}"
  loop: "{{ ipa_hbac_rules }}"

- name: Create Sudo Rules
  freeipa.ansible_freeipa.ipasudorule:
    sudorules: "{{ ipa_sudo_rules }}"
    ipaadmin_password: "{{  ipaadmin_password }}"
  loop: "{{ ipa_hbac_rules }}"
