- name: Configure Global DNS
  freeipa.ansible_freeipa.ipadnsconfig:
    forwarders: "{{ ipa_dns.config.forwarders }}"
    forward_policy: first
    ipaadmin_password: "{{ ipaadmin_password }}"

- name: Create Reverse DNS Zones
  freeipa.ansible_freeipa.ipadnszone:
    name_from_ip: "{{ item.ip }}"
    dynamic_update: "{{ item.dynamic_update }}"
    allow_sync_ptr: "{{ item.allow_sync_ptr }}"
    state: present
    ipaadmin_password: "{{ ipaadmin_password }}"
  loop: "{{ ipa_dns.reverse_zones }}"

- name: Create DNS Zones
  freeipa.ansible_freeipa.ipadnszone:
    name: "{{ item.name }}"
    dynamic_update: "{{ item.dynamic_update }}"
    skip_overlap_check: "{{ item.skip_overlap_check }}"
    allow_sync_ptr: "{{ item.allow_sync_ptr }}"
    update_policy: "grant {{ ipaserver_realm }} krb5-self * A; grant {{ ipaserver_realm }} krb5-self * AAAA; grant {{ ipaserver_realm }} krb5-self * SSHFP;{{ item.update_policy }}"
    state: present
    ipaadmin_password: "{{ ipaadmin_password }}"
  loop: "{{ ipa_dns.zones }}"

- name: Create DNS records
  freeipa.ansible_freeipa.ipadnsrecord:
    ipaadmin_password: "{{ ipaadmin_password }}"
    records: "{{ ipa_dns.records }}"


