- name: Create IPA Hostgroups
  freeipa.ansible_freeipa.ipahostgroup:
    name: "{{ item.name }}"
    state: present
    ipaadmin_password: "{{ ipaadmin_password }}"
  loop: "{{ ipa_hostgroups }}"

- name: Create Services User Groups
  freeipa.ansible_freeipa.ipagroup:
    groups: "{{ ipa_services_groups }}"
    ipaadmin_password: "{{ ipaadmin_password }}"
    
- name: Create IPA User Groups
  freeipa.ansible_freeipa.ipagroup:
    name: "{{ item.name }}"
    description: "{{ item.description | default('Created by Ansible') }}"
    state: present
    ipaadmin_password: "{{ ipaadmin_password }}"
  loop: "{{ ipa_usergroups }}"

- name: Add group membership
  freeipa.ansible_freeipa.ipagroup:
    name: "{{ item.1 }}"
    group: "{{ item.0.name }}"
    state: present
    ipaadmin_password: "{{ ipaadmin_password }}"
  loop: "{{ query('subelements', ipa_usergroups, 'groups', {'skip_missing': True}) }}"
  loop_control:
    label: "{{ item.0.name }} added to {{ item.1 }}"

- name: Create automember rules
  freeipa.ansible_freeipa.ipaautomember:
    name: "{{ item.name }}"
    description: "{{ item.description | default ('created by ansible') }}"
    automember_type: "{{ item.automember_type }}"
    inclusive: "{{ item.inclusive | default([]) }}"
    exclusive: "{{ item.exclusive | default([]) }}"
    state: present
    ipaadmin_password: "{{ ipaadmin_password }}"
  loop: "{{ ipa_automember_rules }}"

- name: Create Service Accounts
  freeipa.ansible_freeipa.ipauser:
    name: "{{ item.name }}"
    first: "{{ item.first }}"
    last: "{{ item.last }}"
    loginshell: "{{ item.loginshell }}"
    passwordexpiration: "{{ item.passwordexpiration }}"
    password: "{{ item.password }}"
    update_password: on_create
    ipaadmin_password: "{{ ipaadmin_password }}"
  loop: "{{ ipa_service_accounts }}"

- name: Add service account group membership
  freeipa.ansible_freeipa.ipagroup:
    name: "{{ item.1 }}"
    user: "{{ item.0.name }}"
    state: present
    ipaadmin_password: "{{ ipaadmin_password }}"
  loop: "{{ query('subelements', ipa_service_accounts, 'groups', {'skip_missing': True}) }}"
  loop_control:
    label: "{{ item.0.name }} added to {{ item.1 }}"

- name: Create IPA permissions
  freeipa.ansible_freeipa.ipapermission:
    name: "{{ item.name }}"
    object_type: "{{ item.object_type }}"
    right: "{{ item.right }}"
    attrs: "{{ item.attrs }}"
    ipaadmin_password: "{{ ipaadmin_password }}"
  loop: "{{ ipa_permissions }}"

- name: Create IPA privileges
  freeipa.ansible_freeipa.ipaprivilege:
    name: "{{ item.name }}"
    permission: "{{ item.permission }}"
    ipaadmin_password: "{{ ipaadmin_password }}"
  loop: "{{ ipa_privileges }}"

- name: Create IPA roles
  freeipa.ansible_freeipa.iparole:
    name: "{{ item.name }}"
    user: "{{ item.user }}"
    privilege: "{{ item.privilege }}"
    ipaadmin_password: "{{ ipaadmin_password }}"
  loop: "{{ ipa_roles }}"

- name: Create HBAC Rules
  freeipa.ansible_freeipa.ipahbacrule:
    name: "{{ item.name }}"
    description: "{{ item.description | default ('created by ansible') }}"
    hostgroup: "{{ item.hostgroup }}"
    group: "{{ item.group }}"
    servicecategory: "{{ item.servicecategory | default('') }}"
    ipaadmin_password: "{{ ipaadmin_password }}"
  loop: "{{ ipa_hbac_rules }}"

- name: Create Sudo Rules
  freeipa.ansible_freeipa.ipasudorule:
    sudorules: "{{ ipa_sudo_rules }}"
    ipaadmin_password: "{{  ipaadmin_password }}"
  loop: "{{ ipa_hbac_rules }}"
