---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: kube-cluster-workers
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: metal3.io/uuid={{ ds.meta_data.uuid }}
          name: '{{ ds.meta_data.name }}'
      users:
      - name: user
        sshAuthorizedKeys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGbzcb23L5wG+IUtsr9ic1MMZPm+bMhlVX6SB2OuaeS9
          asher@infra-kube-1
        sudo: ALL=(ALL) NOPASSWD:ALL
