# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
resources: 
  - ../../../bases/csi-driver-nfs
patches: 

  - target: 
      kind: HelmRelease
    path: nfs-patch.yaml
