- name: Disable resolved
  ansible.builtin.systemd_service:
    name: systemd-resolved
    state: stopped
    masked: true

- name: Remove resolv.conf
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: absent

- name: Touch new resolv
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: touch

- name: Insert dns into /etc/resolv.conf
  ansible.builtin.lineinfile:
    dest: /etc/resolv.conf
    line: "nameserver {{ vm.dns_server }}"

- name: Set timezone to {{ timezone }}
  community.general.timezone:
    name: "{{ timezone }}"

- name: Set SELinux to disabled state
  ansible.posix.selinux:
    state: disabled
  when: ansible_os_family == "RedHat"

- name: Install dependencies
  ansible.builtin.package:
    name:
      - unzip
    state: present

- name: Add IP address of all hosts to all hosts
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{ item }}"
    state: present
  when:
  - item != inventory_hostname
  - hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"

- name: Set SELinux to disabled state
  ansible.posix.selinux:
    state: disabled
  when: ansible_os_family == "RedHat"

- name: Populate service facts
  ansible.builtin.service_facts:
