apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openbao
spec:
  interval: 30m
  chart:
    spec:
      chart: openbao
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: openbao
        namespace: flux-system
      interval: 12h
