packer {
  required_plugins {
    proxmox = {
      version = "~> 1"
      source  = "github.com/hashicorp/proxmox"
    }
    ansible = {
      version = "~> 1"
      source = "github.com/hashicorp/ansible"
    }
  }
}

variable "proxmox_api_url" {
    type = string
}

variable "proxmox_api_token_id" {
    type = string
}

variable "proxmox_api_token_secret" {
    type = string
    sensitive = true
}

variable "vm_id" {
    type = string
}

variable "node" {
    type = string
}

source "proxmox-iso" "autogenerated_1" {
    proxmox_url = "${ var.proxmox_api_url }"
    username = "${ var.proxmox_api_token_id }"
    token = "${ var.proxmox_api_token_secret }"
    insecure_skip_tls_verify = true

    boot_iso {
        type = "scsi"
        iso_file = "ISO:iso/Fedora-Server-dvd-x86_64-41-1.4.iso"
        unmount = true
        iso_storage_pool = "local"
    }

    node = "${ var.node }"
    vm_id = "${ var.vm_id }"
    vm_name = "fedora41"
    template_description = "Fedora 41 Server Image - With IPA Join when appropriately tagged"

    cpu_type = "host"

    qemu_agent = true

    scsi_controller = "virtio-scsi-pci"

    disks {
        disk_size = "30G"
        format = "raw"
        storage_pool = "local-lvm"
        # storage_pool_type = "zfs"
        type = "virtio"
    }

    # VM CPU Settings
    cores = "2"
    
    # VM Memory Settings
    memory = "4096" 

    # VM Network Settings
    network_adapters {
        model = "virtio"
        bridge = "svcnet"
        firewall = "false"
    } 
    
    boot_command = ["<up>e<down><down><end> text inst.ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/inst.ks<f10><wait>"]
    boot_wait    = "10s"
    communicator            = "ssh"

    http_directory          = "http" 

    ssh_username            = "cloud-user"
    ssh_private_key_file    = "~/.ssh/id_ed25519"

    ssh_timeout             = "30m"
    ssh_pty                 = true

    # VM Cloud-Init Settings
    cloud_init = true
    cloud_init_storage_pool = "local-lvm"
}

build {
    sources = ["source.proxmox-iso.autogenerated_1"]
  
    name = "proxmox-rl9"

    provisioner "shell" {
        inline = [
            "sudo rm /etc/ssh/ssh_host_*",
            "sudo truncate -s 0 /etc/machine-id",
            "sudo cloud-init clean",
            "sudo rm -f /etc/cloud/cloud.cfg.d/subiquity-disable-cloudinit-networking.cfg",
            "sudo rm -f /etc/netplan/00-installer-config.yaml",
            "sudo sync",
        ]
    }

    provisioner "ansible" {
      playbook_file = "../../ansible/ipajoin.yaml"
      use_proxy = false
    }

    provisioner "ansible" {
      playbook_file = "../../ansible/growroot.yaml"
      use_proxy = false
    }
}
