- name: Check if vault is initialized
  ansible.builtin.shell: "vault status -format=json"
  register: vault_status
  failed_when: vault_status.rc == 1
  changed_when: false
  environment:
    VAULT_ADDR: "{{ vault_address }}"

- name: Initial Vault config
  environment:
    VAULT_ADDR: "{{ vault_address }}"
  when: vault_status.stdout | from_json | json_query('initialized') | bool == false
  block:
    - name: Initialize vault
      ansible.builtin.shell: "vault operator init -key-shares={{ vault_key_portions }} -key-threshold={{ vault_key_threshold }} -format=json"
      register: vault_init
      changed_when: vault_init.rc == 0
    
    - name: Get unseal keys
      set_fact:
        unseal_keys: "{{ vault_init.stdout | from_json | json_query('unseal_keys_b64') }}"

    - name: Debug unseal keys
      ansible.builtin.debug:
        var: unseal_keys
    
    - name: Unseal vault
      ansible.builtin.shell: "vault operator unseal {{ item }}"
      register: vault_unseal
      changed_when: vault_unseal.rc == 0
      loop: "{{ unseal_keys }}"
