- name: Create IP Tables forwarding rule 
  ansible.builtin.iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    match: tcp
    destination_port: "{{ vault_forward_port }}"
    jump: REDIRECT
    to_ports: 8200

- name: Save current state of the firewall in system file
  community.general.iptables_state:
    state: saved
    path: "{{ iptables_config_path }}"

- name: Template IPtables Restore
  ansible.builtin.template:
    src: iptables-restore.service.j2
    dest: /etc/systemd/system/iptables-restore.service

- name: Enable iptables service
  ansible.builtin.systemd_service:
    name: iptables-restore
    daemon_reload: true
    enabled: true
