- name: Configure policies
  environment:
    VAULT_ADDR: "{{ vault_address }}"
    VAULT_TOKEN: "{{ vault_token }}"
  block:
    - name: Enable User Pass
      ansible.builtin.shell: "vault auth enable userpass"
      register: out
      changed_when: out.rc == 0
      failed_when: out.rc != 0 and out.rc != 2

    - name: Create admin service account
      ansible.builtin.shell: "vault write auth/userpass/users/{{ vault_svc_account.name }} password={{ vault_svc_account.password }} policies=admin"
      register: vault_svc_account_out
      changed_when: vault_svc_account_out.rc == 0
