- name: Login using svc account
  community.hashi_vault.vault_login:
    url: "{{ vault_address }}"
    auth_method: userpass
    username: "{{ vault_svc_account.name }}"
    password: '{{ vault_svc_account.password }}'
  register: login_data

- name: Set Vault token variable
  ansible.builtin.set_fact:
    vault_token: "{{ login_data.login.auth.client_token }}"
