# Ansible details
ansible_user: cloud-user
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

#Node details
#These are the nodes that the vm's will be deployed to, in sequential order, eg. master01 will be deployed to nodes[0]. Use proxmox node names
vm:
  target_nodes: ["vm01","vm02"] # List of nodes to deploy the masters to must match master count (max )
  templates: [9000,9001]
  count: 2
  cpu: 4
  memory: 4096
  disk_size: 30 # Disk size for root drive of VM in GB
  storage_pool: "local-lvm"
  bridge: "vmbr0"
  tag: 4000
  tags: "infra"
  dns_server: 1.1.1.1
  search_domain: infra.ashman.world # Not currently being used because proxmox is broken
  ssh_pub_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF6leLiXjd46rW2/bKTyFtEBXv8A47Ti0kd49CcexgLy asher@fedora
  network_gateway: "10.110.0.1"
  network_subnet: "10.110.0.0"
  network_mask: "24"
  network_start_ip: "10"
  description: "FreeIPA hosts deployed by terraform"

#Hostname details
service_name: ipa
dns_zone: infra.ashman.world

# IPA Server Details
ipaserver_domain: infra.ashman.world
ipaserver_realm: INFRA.ASHMAN.WORLD
ipaserver_setup_dns: true
ipaserver_setup_ca: true
ipaserver_auto_forwarders: true
ipaserver_allow_zone_overlap: true
ipaadmin_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34666436383862653562663731616564346365643766636532333932656363343039663133663930
          3764393962633637633062366539653539333465373038610a636164353639366236326562653866
          65323862353632393363633734646164356133376364343739393130613035383162343562363664
          6238666566303339650a303038346162393530326435363037663334343334646162313939353064
          65616365326634393133393337643930366434626664323964656461653239323534
ipadm_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39346162306233643637373435646634653537316430653462343537346463373137313233653438
          3964376165643464616531396530633632653965323563360a636138393863383934316262326436
          34613335353264663162393230663233393131626131646164646237653734346565336130353766
          6161663633306135650a323164636538366562313934313432663331636263313761316533653962
          37623530346365383738356562326162646439613835343537396432353765626336

# IPA Client
ipaclient_force_join: true
ipaclient_mkhomedir: true

# IPA Replica Details
ipareplica_allow_zone_overlap: true
ipareplica_setup_dns: true
ipareplica_setup_ca: true
ipareplica_auto_forwarders: true

ipa_dns:
  config:
    forwarders:
      - ip_address: 1.1.1.1
      - ip_address: 8.8.8.8
  reverse_zones:
    - ip: 10.140.0.0/22
      dynamic_update: true
      allow_sync_ptr: true
    - ip: 10.110.0.0/24
      dynamic_update: true
      allow_sync_ptr: true
  zones:
    - name: svc.ashman.world
      dynamic_update: true
      allow_sync_ptr: true
      skip_overlap_check: false
    - name: k8s.ashman.world
      dynamic_update: true
      allow_sync_ptr: true
      skip_overlap_check: false
    - name: ashman.world
      dynamic_update: true
      allow_sync_ptr: true
      skip_overlap_check: true
  records:
    - zone_name: infra.ashman.world
      name: qdev01
      record_type: A
      record_value:
        - 10.110.0.53
    - zone_name: infra.ashman.world
      name: vm01
      record_type: A
      record_value:
        - 10.110.0.50
    - zone_name: infra.ashman.world
      name: vm02
      record_type: A
      record_value:
        - 10.110.0.51
    - zone_name: infra.ashman.world
      name: pmtp
      record_type: A
      record_value:
        - 10.110.0.53
    - zone_name: infra.ashman.world
      name: storage
      record_type: A
      record_value:
        - 10.110.0.20
    - zone_name: infra.ashman.world
      name: pihole
      record_type: A
      record_value:
        - 10.110.0.100
    - zone_name: infra.ashman.world
      name: router
      record_type: A
      record_value:
        - 10.110.0.1
          

ipa_service_accounts:
  - name: svc-host-enroll
    first: Host
    last: Enroll
    loginshell: "/sbin/nologin"
    passwordexpiration: "2099-01-01 23:59:59"
    password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39643839663731386662303438363061346633393062663162376137333865633863636161616630
          6364383539646366333630326130636638313336396335370a316135393466326336366366373734
          31633264306164366138313965353664363164613365353436333765656130333839613463393433
          3064623238373335370a303266626336316431613664626362646133356263373134656365363431
          33386364386461663032623461663938393734616131363135613132333232636139
  - name: svc-ansible-infra
    first: Ansible
    last: Infrastructure
    loginshell: "/bin/bash"
    passwordexpiration: "2099-01-01 23:59:59"
    password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36333164333964313338343636363565616365626234623533393130333637393233333636636438
          6436613861353734306635383634303733323735623034650a343063656265643338643964616332
          32666136616130646233626135366165376466353464326363663161616637356465666461613264
          6563303435396561330a633433313761333562356532323262343831306564626230306330306435
          32373936656530613139623235646533316464613831323963373330376139373864

ipa_permissions:
  - name: "Modify Host - Description"
    object_type: host
    right: write
    attrs:
      - description

ipa_privileges:
  - name: "Host Enrollment"
    permission:
    - "Modify Host - Description"
    - "System: Add Hosts"
    - "System: Add krbPrincipalName to a Host"
    - "System: Enroll a Host"
    - "System: Manage Host Certificates"
    - "System: Manage Host Enrollment Password"
    - "System: Manage Host Keytab"
    - "System: Manage Host Principals"

ipa_roles:
  - name: HostEnroll
    user:
      - svc-host-enroll
    privilege:
      - 'Host Enrollment'

ipa_usergroups:
  - name: services-admins
  - name: k8s-admins
  - name: infra-admins
  - name: media-users
  - name: media-admins

ipa_hostgroups:
  - name: services
  - name: kubernetes
  - name: infrastructure

ipa_automember_rules:
  - name: services
    description: "Automember condition for svc domain"
    automember_type: hostgroup
    inclusive:
      - key: fqdn
        expression: "^.*.svc.ashman.world$"
  - name: kubernetes
    description: "Automember condition for k8s domain"
    automember_type: hostgroup
    inclusive:
      - key: fqdn
        expression: "^.*.k8s.ashman.world$"
  - name: infrastructure
    description: "Automember condition for infrastructure domain"
    automember_type: hostgroup
    inclusive:
      - key: fqdn
        expression: "^.*.infra.ashman.world$"
    exclusive:
      - key: fqdn
        expression: "^ipa.*.infra.ashman.world$"
  - name: infra-admins
    description: "Automember condition for infra-admins"
    automember_type: group
    inclusive:
      - key: uid
        expression: "^svc\\-.*\\-infra$"

ipa_hbac_rules:
  - name: services_admins_allow
    description: "Allow services-admins access to services hostgroup"
    hostgroup:
      - services
    group:
      - services-admins
    servicecategory: all
  - name: k8s_admins_allow
    description: "Allow k8s-admins access to kubernetes hostgroup"
    hostgroup:
      - kubernetes
    group:
      - k8s-admins
    servicecategory: all
  - name: infra_admins_allow
    description: "Allow infra-admins access to infrastructure hostgroup"
    hostgroup:
      - infrastructure
    group:
      - infra-admins
    servicecategory: all

ipa_sudo_rules:
  - name: services_admin_all
    description: "Allow services-admins to run sudo on services hosts"
    hostgroup:
      - services
    group:
      - services-admins
    cmdcategory: all
  - name: k8s_admins_all
    description: "Allow k8s-admins run sudo on kubernetes hostrgoup"
    hostgroup:
      - kubernetes
    group:
      - k8s-admins
    cmdcategory: all
  - name: infra_admins_all
    description: "Allow infra-admins run sudo on infrastructure hostrgoup"
    hostgroup:
      - infrastructure
    group:
      - infra-admins
    cmdcategory: all


