# Ansible details
timezone: "Australia/Melbourne"
ansible_user: svc-ansible-infra
ansible_ssh_pass: "{{ vault_ipa_service_accounts.svc_ansible_infra.password }}"
ansible_become_pass: "{{ vault_ipa_service_accounts.svc_ansible_infra.password }}"
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

#Node details
#These are the nodes that the vm's will be deployed to, in sequential order, eg. master01 will be deployed to nodes[0]. Use proxmox node names
vm:
  target_nodes: ["vm01","vm02", "vm03"] # List of nodes to deploy the masters to must match master count (max )
  template: fedora41
  count: 3
  primary_count: 3
  cpu: 8
  memory: 12228
  disk_size: 200 # Disk size for root drive of VM in GB
  storage_pool: "local-lvm"
  bridge: "vmbr0"
  tag: 4000
  tags: "ipajoined,infra"
  dns_server: "10.110.0.10 10.110.0.11 10.110.0.12"
  search_domain: infra.ashman.world
  ssh_pub_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF6leLiXjd46rW2/bKTyFtEBXv8A47Ti0kd49CcexgLy asher@fedora
  network_gateway: "{{ network.infra.gateway }}"
  network_subnet: "{{ network.infra.subnet }}"
  network_mask: "{{ network.infra.mask }}"
  network_start_ip: "{{ network.infra.start_ip.k8s }}"
  description: "Minio hosts deployed by terraform"
  additional_networks:
    - bridge: "svcnet"
      firewall: false
      tag: 0


#Hostname details
service_name: kube-infra
dns_zone: infra.ashman.world

# RKE2 Variables
rke2_ha_mode: true
rke2_ha_mode_keepalived: false
rke2_ha_mode_kubevip: true
rke2_api_ip: 10.110.0.150
rke2_kubevip_cloud_provider_enable: false
rke2_kubevip_svc_enable: false
rke2_version: v1.32.0+rke2r1 
#rke2_loadbalancer_ip_range:
#  range-global: 10.110.0.200-10.110.0.254
rke2_custom_manifests:
  - templates/rke2-cilium-config.yaml
  #  - templates/cilium-l2-policy.yaml
  #  - templates/cilium-lb-pool.yaml
  #  - templates/cilium-host-access-policy.yaml
rke2_cni:
  - multus
  - cilium
disable_kube_proxy: true
#k8s_node_label:
#  - node-access: minimum-access
rke2_selinux: false
rke2_disable:
  - rke2-metrics-server
  - rke2-ingress-nginx
rke2_cluster_group_name: k8s_cluster
rke2_servers_group_name: k8s_masters
rke2_agents_group_name: k8s_workers
rke2_download_kubeconf: true
rke2_download_kubeconf_path: /home/asher/.kube
rke2_download_kubeconf_file_name: rke2-kubeconfig.yaml
