- name: Deploy infrastructure
  hosts: localhost
  tasks:
  - name: Deploy pihole nodes on proxmox
    community.general.terraform: 
      project_path: ../../terraform
      state: present
      force_init: true
      complex_vars: true
      variables:
        dns_server: "{{ dns_server }}"
        proxmox_host: "{{ proxmox_host }}"
        proxmox_user: "{{ proxmox_user }}"
        proxmox_password: "{{ proxmox_password }}"
        proxmox_datastore_id: "{{ proxmox_datastore_id }}"
        vm_user: "{{ ansible_user }}"
        vm_user_ssh_key: "{{ ssh_pub_key }}"
        vm_template_id: "{{ vm_template_id }}"
        master_nodes: "{{ master_nodes }}"
        master_count: "{{ master_count }}"
        master_cpu: "{{ master_cpu }}"
        master_memory: "{{ master_memory }}"
        tags: "{{ vm_tags }}"
        disk_size: "{{ disk_size }}"
        storage_pool: "{{ storage_pool }}"
        bridge: "{{ bridge }}"
        tag: "{{ tag }}"
        #     cloud_image: "{{ cloud_image_url }}"
        #        vm_id: "{{ vm_id }}"
        service_name: "{{ service_name }}"
        #reverse_zone: "{{ reverse_zone }}"
    register: tf_out 
     
  - meta: refresh_inventory

  - name: Wait for each host to be joined in IPA
    ansible.builtin.command: ipa host-show "{{ item }}"
    register: host_show_out
    retries: 60
    delay: 5
    until: host_show_out.rc == 0 and host_show_out.stdout_lines | regex_search("Keytab{{':'}} True") != ""
    loop: "{{ groups['pihole_cluster'] | list }}"

  - name: Wait for pihole servers to come up
    ansible.builtin.pause:
      seconds: 60

    #- name: Wait for hosts to come up
    #  hosts: pihole_cluster
    #  gather_facts: false
    #  tasks:
    #  - name: Wait for pihole servers to come up
    #    ansible.builtin.pause:
    #      seconds: 30


  #    ansible.builtin.wait_for_connection:
  #      delay: 5
  #      timeout: 60
