- name: Disable systemd-resolved
  hosts: pihole_cluster
  become: true
  tasks:
    - name: Disable resolved
      ansible.builtin.systemd_service:
        name: systemd-resolved
        state: stopped
        masked: true

    - name: Remove resolv.conf
      ansible.builtin.file:
        path: /etc/resolv.conf
        state: absent

    - name: Touch new resolv
      ansible.builtin.file:
        path: /etc/resolv.conf
        state: touch

    - name: Insert dns into /etc/resolv.conf
      ansible.builtin.lineinfile:
        dest: /etc/resolv.conf
        line: "nameserver {{ dns_server }}"



