---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./kubernetes/infrastructure/overlays/applications/keycloak
  dependsOn: 
    - name: repositories
    - name: cloudnative-pg

  prune: true
  sourceRef:
    kind: "GitRepository"
    name: "flux-system"
