---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metal3
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./kubernetes/infrastructure/overlays/applications/metal3

  prune: false
  sourceRef:
    kind: "GitRepository"
    name: "flux-system"
