---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minio
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./kubernetes/infrastructure/overlays/applications/minio
  dependsOn: 
    - name: repositories

  prune: true
  sourceRef:
    kind: "GitRepository"
    name: "flux-system"
