---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openbao
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./kubernetes/infrastructure/overlays/applications/openbao

  prune: true
  sourceRef:
    kind: "GitRepository"
    name: "flux-system"
