---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: projectsveltos
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./kubernetes/infrastructure/overlays/applications/projectsveltos
  dependsOn: 
    - name: repositories
    - name: metal3

  prune: true
  sourceRef:
    kind: "GitRepository"
    name: "flux-system"
