- name: Deploy Pihole infrastructure
  hosts: localhost
  vars_files:
    - inventory/vars/pihole.yaml
  tasks:
    - name: Deploy nodes on proxmox
      ansible.builtin.include_role:
        name: proxmox_nodes
      vars:
        state: present

    - meta: refresh_inventory

    - name: Wait for each host to be joined in IPA
      ansible.builtin.include_role:
        name: wait_host_joined
      vars:
        joined_hosts: "{{ groups['pihole_cluster'] | list }}" 

- name: Deploy Pihole
  hosts: pihole_cluster
  become: true
  gather_facts: true
  vars_files:
    - inventory/vars/pihole.yaml
  roles:
    - /home/asher/Development/ansible/roles/pihole-ansible-role

    #    - pihole-ansible-role
