- name: Deploy Minio infrastructure
  hosts: localhost
  vars_files:
    - inventory/vars/vault.yaml
  tasks:
    - name: Deploy nodes on proxmox
      ansible.builtin.include_role:
        name: proxmox_nodes
      vars:
        state: present

    - meta: refresh_inventory

    - name: Wait for each host to be joined in IPA
      ansible.builtin.include_role:
        name: wait_host_joined
      vars:
        joined_hosts: "{{ groups['minio'] | list }}" 

    - name: Short delay for final stages of join
      ansible.builtin.pause:
        seconds: 5

- name: Prepare vault for deployment
  hosts: vault
  become: true
  gather_facts: false
  vars_files:
    - inventory/vars/vault.yaml
  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.core_dependencies
    - role: robertdebock.hashicorp

- name: Deploy Vault
  hosts: vault
  become: true
  gather_facts: true
  vars_files:
    - inventory/vars/vault.yaml
  tasks:
    - name: Create IP Tables forwarding rule 
      ansible.builtin.iptables:
      table: nat
      chain: PREROUTING
      protocol: tcp
      match: tcp
      destination_port: 443
      jump: REDIRECT
      to_ports: 8200

    - name: Run Vault  
      ansible.builtin.include_role:
        name: robertdebock.vault
