- name: Deploy Pihole infrastructure
  hosts: localhost
  vars_files:
    - inventory/vars/k8s.yaml
  tasks:
    - name: Deploy nodes on proxmox
      ansible.builtin.include_role:
        name: proxmox_nodes
      vars:
        state: present

    - meta: refresh_inventory

    - name: Wait for each host to be joined in IPA
      ansible.builtin.include_role:
        name: wait_host_joined
      vars:
        joined_hosts: "{{ groups['k8s_cluster'] | list }}" 

    - name: Short delay for final stages of join
      ansible.builtin.pause:
        seconds: 5

- name: Deploy K8S (RKE2)
  hosts: k8s_cluster
  become: true
  gather_facts: true
  vars_files:
    - inventory/vars/k8s.yaml
  roles:
  tasks:
    - name: Disable firewalld
      ansible.builtin.systemd_service:
        name: firewalld
        enabled: false
        state: stopped
        masked: true

    - name: Install node requirements
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - iscsi-initiator-utils
        - cryptsetup

    - name: Start and enable services
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - iscsid

    - name: Enable dm_crypt kernel module
      community.general.modprobe:
        name: dm_crypt
        state: present
        persistent: present

    - name: Deploy RKE2
      ansible.builtin.include_role:
        name: lablabs.rke2

