- name: Deploy infrastructure
  hosts: localhost
  vars_files:
    - inventory/vars/k8s.yaml
  tasks:
    - name: Destroy nodes on proxmox
      ansible.builtin.include_role:
        name: proxmox_nodes
      vars:
        state: absent
