apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
resources:
- ../../../bases/keycloak
- postgres.yaml
- namespace.yaml
- servertransport.yaml
patches:
- target:
    kind: HelmRelease
  path: keycloak-patch.yaml

