apiVersion: v1
kind: Secret
metadata:
  name: bml-01
type: Opaque
stringData:
  username: replaceme
  password: replaceme
---
apiVersion: v1
kind: Secret
metadata:
  name: bml-02
type: Opaque
stringData:
  username: replaceme
  password: replaceme
