apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: clusters
resources: 
#  - namespace.yaml
  - ../../../bases/kubeadm
  #  - ./hosts
  #  - bootstrap-kustomization.yaml

patches: 
- target:
    kind: Cluster
  path: patches/cluster.yaml
- target:
    kind: KubeadmConfigTemplate
  path: ./patches/kubeadmconfig-patch.yaml
- target: 
    kind: KubeadmControlPlane
  path: ./patches/kubeadmcontrolplane-patch.yaml
    #  patch: | 
    #    - op: add 
    #      path: /metadata/annotations
    #      value: 
    #        controlplane.cluster.x-k8s.io/skip-kube-proxy: true
  
- target: 
    kind: Cluster
  patch: | 
    - op: replace
      path: /spec/controlPlaneRef/namespace
      value: clusters
- target: 
    kind: Cluster
  patch: | 
    - op: replace
      path: /spec/infrastructureRef/namespace
      value: clusters
