apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
  - ../../bases/kubeadm

patches: 
- target: 
    kind: KubeadmControlPlane 
  patch: | 
    - op: replace
      path: /spec/machineTemplate/infrastructureRef/name
      value: kube-cluster-v1.30.2-controlplane
- target: 
    kind: MachineDeployment
  patch: | 
    - op: replace
      path: /spec/template/spec/infrastructureRef/name
      value: kube-cluster-v1.30.2-workers
