apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: baremetal-prod
resources: 
  - namespace.yaml
  - ../../../bases/kubeadm
  #  - ./hosts
  - bootstrap-kustomization.yaml

patches: 
- target: 
    kind: Cluster
  patch: | 
    - op: replace
      path: /spec/controlPlaneRef/namespace
      value: baremetal-prod
- target: 
    kind: Cluster
  patch: | 
    - op: replace
      path: /spec/infrastructureRef/namespace
      value: baremetal-prod
