apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
spec:
  interval: 30m
  chart:
    spec:
      chart: vault
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: vault
        namespace: flux-system
      interval: 12h
