apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
resources:
  - ../../../bases/vault
  - namespace.yaml

patches:
  - target:
      kind: HelmRelease
    path: ./vault-patch.yaml
